# Generated by Django 6.0.2 on 2026-02-09

from django.db import migrations, models


class Migration(migrations.Migration):

    """Crea el catálogo con el esquema mínimo inicial."""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sku", models.CharField(db_comment="Identificador estable usado entre sistemas", max_length=40, unique=True)),
                ("name", models.CharField(db_comment="Nombre comercial del producto", max_length=120)),
                ("price", models.IntegerField(db_comment="Precio inicial expresado en unidades enteras")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_comment="Timestamp de creación del registro")),
            ],
            options={
                "db_table": "catalog_product",
                "ordering": ["name"],
            },
        ),
    ]
